version: '3.0'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'todo-bolttech'
      MYSQL_USER: 'api-client'
      MYSQL_PASSWORD: 'pa!ssword'
      MYSQL_ROOT_PASSWORD: 'pass!word'
    ports:
      - '3306:3306'
  client:
    build:
      context: ./client
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/bolttech-challenge/client
      - /usr/src/bolttech-challenge/client/node_modules